default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: databaseuser
  password: databaseuser
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: realtime_search_development

test:
  <<: *default
  database: realtime_search_test

production:
  <<: *default
  database: realtime_search_production
  username: realtime_search
  password: <%= ENV["REALTIME_SEARCH_DATABASE_PASSWORD"] %>
